### ISSUE TITLE
Oracle java Fatal error "set alternative failed"

### ISSUE THREAD

**Issue by erikthorselius** [cookbooks/java#4]
Hi, I'm trying to install java oracle 7 on ubuntu but i receive an error.
I receive the same error on opscode-ubuntu-1204 and precise64. 
If I try the same code on Berkshelf-CentOS-6.3-x86_64-minimal it works fine. 

Here is the installation log:

```
[2013-07-11T14:37:44+00:00] INFO: Processing directory[/etc/profile.d] action create (java::set_java_home line 26)
[2013-07-11T14:37:44+00:00] INFO: Processing file[/etc/profile.d/jdk.sh] action create (java::set_java_home line 30)
[2013-07-11T14:37:44+00:00] INFO: Processing java_ark[jdk] action install (java::oracle line 47)
[2013-07-11T14:37:44+00:00] FATAL:  set alternative failed


================================================================================

Error executing action `install` on resource 'java_ark[jdk]'

================================================================================




SystemExit

----------

exit




Cookbook Trace:

---------------
/tmp/vagrant-chef-1/chef-solo-1/cookbooks/java/providers/ark.rb:218:in `block (3 levels) in class_from_file'
/tmp/vagrant-chef-1/chef-solo-1/cookbooks/java/providers/ark.rb:214:in `block (2 levels) in class_from_file'
/tmp/vagrant-chef-1/chef-solo-1/cookbooks/java/providers/ark.rb:204:in `each'
/tmp/vagrant-chef-1/chef-solo-1/cookbooks/java/providers/ark.rb:204:in `block in class_from_file'


Resource Declaration:
---------------------
# In /tmp/vagrant-chef-1/chef-solo-1/cookbooks/java/recipes/oracle.rb

 47: java_ark "jdk" do
 48:   url tarball_url
 49:   checksum tarball_checksum
 50:   app_home java_home
 51:   bin_cmds bin_cmds
 52:   alternatives_priority 1062
 53:   action :install
 54: end
 55:



Compiled Resource:
------------------
# Declared in /tmp/vagrant-chef-1/chef-solo-1/cookbooks/java/recipes/oracle.rb:47:in `from_file'

java_ark("jdk") do
  action [:install]
  updated true
  updated_by_last_action true
  supports {:report=>true, :exception=>true}
  retries 0
  retry_delay 2
  cookbook_name :java
  recipe_name "oracle"
  url "http://download.oracle.com/otn-pub/java/jdk/7u25-b15/jdk-7u25-linux-i586.tar.gz"
  checksum "dd89b20afa939992bb7fdc44837fa64f0a98d7ee1e5706fe8a2d9e2247ba6de7"
  app_home "/opt/app/dcim/java/jdk7"
  bin_cmds ["appletviewer", "apt", "ControlPanel", "extcheck", "idlj", "jar", "jarsigner", "java", "javac", "javadoc", "javafxpackager", "javah", "javap", "javaws", "jcmd", "jconsole", "jcontrol", "jdb", "jhat", "jinfo", "jmap", "jps", "jrunscript", "jsadebugd", "jstack", "jstat", "jstatd", "jvisualvm", "keytool", "native2ascii", "orbd", "pack200", "policytool", "rmic", "rmid", "rmiregistry", "schemagen", "serialver", "servertool", "tnameserv", "unpack200", "wsgen", "wsimport", "xjc"]
  alternatives_priority 1062
  default true
end



[2013-07-11T14:37:44+00:00] INFO: Running queued delayed notifications before re-raising exception
[2013-07-11T14:37:44+00:00] ERROR: Running exception handlers
[2013-07-11T14:37:44+00:00] ERROR: Exception handlers complete
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

The Berksfile.lock

```
{
  "sources": {
    "somc-java": {
      "path": "."
    },
    "java": {
      "locked_version": "1.12.0"
    },
    "windows": {
      "locked_version": "1.10.0"
    },
    "chef_handler": {
      "locked_version": "1.1.4"
    }
  }
}
```

I'm using both config.berkshelf.enabled = true and config.omnibus.chef_version = :latest in vagrant. 

Vagrant version 1.1.4
Chef version 11.4.4

**Comment by erikthorselius** [comment]
Sorry for the report, the node.default['java']['java_home'] path was a folder already created in the recipe. So when the ark.rb tried to symlink the file the directory levels where wrong and update-alternatives could not find the files.
